name: Java CI

on:
  push:
    branches: [ javaci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file C:/Users/rbravo/Developer/MisProyectos/myProjects/javaci/myProjects/prueba/pom.xml